### ISSUE TITLE
`seek_before` parameters are inconsistent between `BinRead` and `BinWrite`

### ISSUE THREAD

**Issue by tech-ticks** [jam1garner/binrw#201]
Using `seek_before` on a `brw` attribute seems impossible when a field in the struct is accessed because the `br` variant passes struct fields by value while `bw` passes by reference.

This code doesn't compile:
```rust
#[binrw]
pub struct Foo {
    pub count: u32,
    pub data_offset: u32,
    #[brw(seek_before(SeekFrom::Current(data_offset.into())))]
    #[br(count = count)]
    pub data: Vec<u8>,
}
```

Neither does this code:
```rust
#[binrw]
pub struct Foo {
    pub count: u32,
    pub data_offset: u32,
    #[brw(seek_before(SeekFrom::Current((*data_offset).into())))]
    #[br(count = count)]
    pub data: Vec<u8>,
}
```

The only simple way around this is to split the `brw` attribute into two:
```rust
#[binrw]
pub struct Foo {
    pub count: u32,
    pub data_offset: u32,
    #[br(seek_before(SeekFrom::Current(data_offset.into())))]
    #[bw(seek_before(SeekFrom::Current((*data_offset).into())))]
    #[br(count = count)]
    pub data: Vec<u8>,
}
```

**Comment by csnover** [comment]
That’s correct. This is largely a limitation of the ownership model of Rust, since `BinRead` must use move semantics to support transferring ownership of data that is not `Clone`, and `BinWrite` must use borrow semantics for the same reason (and to avoid making unnecessary copies of data). I’m not sure offhand of a generalisable rule that would make it possible to reference fields in `brw` without causing more confusion, but am open to suggestions.

**Comment by csnover** [comment]
Since this is an issue with variable references in `#[brw]` attributes in general, I will merge this with #179 and treat that as the ticket for the root problem.
