### ISSUE TITLE
Strict pre_assert

### ISSUE THREAD

**Issue by v1gnesh** [jam1garner/binrw#281]
It seems that when binrw goes into an enum variant based on a `pre_assert`, and then if there are insufficient bytes to read/process an enum variant (say a struct) entirely, it just tries out the other enum variants in the defined order.

When I have `None` at the end (which I want to use for some actual variants based on specific pre_asserts), the above insufficient input bytes condition leads to the enum variant of `None` being selected.

Meaning, although I have `pre_assert` to request binrw to go to one arm, it fails over to try other variants, instead of bubbling up the error it encountered within a specific enum variant (ex: Not enough bytes to parse 'x').

So, is it possible to create a stricter variant, say `strict_pre_assert` or whatever, so that it stops there & sends the error up, instead of continuing and trying if other variants work (ignoring the supplied `pre_assert`)?

**Comment by csnover** [comment]
Thanks for your report! On the surface I understand the request but as I think about the situation where it would be used I feel uncertainty about how the existing mechanism doesn’t work for you and maybe need a more specific example.

Regarding the error reporting: Per-variant errors are collected unless you specify [`return_unexpected_error`](https://docs.rs/binrw/latest/binrw/docs/attribute/index.html#enum-errors), so you should be seeing the error you want already by default.

Regarding control flow: If you are using `pre_assert` to pick the right variant, then it shouldn’t be the case that other unrelated variants would try to parse, unless your `pre_assert` condition isn’t correct. To that end, putting `pre_assert(false)` on the last variant would keep the parser from selecting that variant, and would result in a failed parse if it got there.

I can certainly imagine how to extend `pre_assert` by using some signalling mechanism like [`ControlFlow<bool, bool>`](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html) instead of adding a separate directive, but I don’t know understand yet how this is going to solve your problem versus using `pre_assert(false)`.

Let me know. Thanks!

**Comment by v1gnesh** [comment]
> Regarding control flow: If you are using pre_assert to pick the right variant, then it shouldn’t be the case that other unrelated variants would try to parse, 

But it do be like that. I can show the related convo in the Discord/Matrix.

**Comment by csnover** [comment]
> But it do be like that. I can show the related convo in the Discord/Matrix.

Yes, please provide the example here. If `pre_assert` is selecting variants when the condition is `false`, that sounds like a bug.

Unfortunately, the Matrix and Discord channels are no longer bridged due to an [error that occurred with the t2bot service](https://t2bot.io/blog/2024/01/14/discord-bridge-reset/) in January, and I am unable to restore the bridge, so am only able to reply to messages here and on Matrix.

> I can't use `pre_assert(false)` in this case as I need the None variant to be selected in some cases.

What makes it so that you cannot provide an expression to the pre-condition that will return `true` in those cases?

Thanks!

**Comment by v1gnesh** [comment]
> What makes it so that you cannot provide an expression to the pre-condition that will return true in those cases?

Huh, I can. Seems I removed the conditional fall-back logic to `None` that is required.
Meaning, I don't have a "default" None type that will allow silent failure.

While I try to recreate a basic example, I hope this helps in the meantime:

<details>
<summary>discord snip</summary>

![Screenshot from 2024-08-08 13-38-14](https://github.com/user-attachments/assets/5064cb84-9967-4190-a4b7-c9551e821175)


</details>

**Comment by csnover** [comment]
Enum parsing doesn’t “swallow errors” unless error collection is explicitly disabled. They are collected into `Error::EnumErrors::variant_errors` collection, which gets chained into `Error::Backtrace` like any other sub-object error. But `pre_assert` isn’t an error condition, it’s just flow control. Probably this directive should have been named `if` rather than `pre_assert`, since “assert” implies some invariant check that may result in an error, which is not the case.

**Comment by v1gnesh** [comment]
Yeah, I think I can chalk this to my mistake per my above comment. I'll close this off.
Thanks again for checking!

**Comment by csnover** [comment]
Awesome, glad you were able to figure it out! :-)
