### ISSUE TITLE
Is `#[brw(map=map_fn)]` possible?

### ISSUE THREAD

**Issue by Neutron3529** [jam1garner/binrw#282]
Currently, when I wrote #[brw(map=map_fn)], some unexpected things happens:
```rust
    #[bw(map=round_yaw)]
    pub yaw: f32,
// it generates
error[E0277]: the trait bound `(): Borrow<f32>` is not satisfied
   --> src/data/building.rs:66:15
    |
66  |     #[brw(map=round_yaw)]
    |               ^^^^^^^^^ the trait `Borrow<f32>` is not implemented for `()`
    |
note: required by a bound in `round_yaw`
   --> src/lib.rs:289:31
    |
289 |     pub fn round_yaw(val:impl std::borrow::Borrow<f32>) -> f32 {round(*val.borrow(),1)}
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `round_yaw`

```
I have to wrote
```rust
    #[br(map=|x:f32|round_yaw(x))]
    #[bw(map=|x|round_yaw(x))]
    pub yaw: f32,
```
to make the program happy.

It seems br and bw cannot accept a same function (since bw needs a `&T`, but br needs `T`. force bw accept `T` is a hard error:)
```rust
error[E0631]: type mismatch in closure arguments
   --> src/data/building.rs:67:14
    |
43  | #[derive(BinRead, BinWrite)]
    |                   -------- required by a bound introduced by this call
...
67  |     #[bw(map=|x:f32|round_yaw(x))]
    |              -------^^^^^^^^^^^^
    |              |
    |              expected due to this
    |              found signature defined here
    |
    = note: expected closure signature `fn(&_) -> _`
               found closure signature `fn(_) -> _`
note: required by a bound in `write_map_fn_input_type_hint`
   --> /home/neutron/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/binrw-0.14.0/src/private.rs:221:29
    |
219 | pub fn write_map_fn_input_type_hint<Input, Output, MapFn>(func: MapFn) -> MapFn
    |        ---------------------------- required by a bound in this function
220 | where
221 |     MapFn: FnOnce(Input) -> Output,
    |                             ^^^^^^ required by this bound in `write_map_fn_input_type_hint`
help: consider adjusting the signature so it borrows its argument
    |
67  |     #[bw(map=|x:&f32|round_yaw(x))]
    |                 +
```
and it cannot force br accept a &T object:
```rust
error[E0277]: the trait bound `&f32: BinRead` is not satisfied
  --> src/data/building.rs:43:10
   |
43 | #[derive(BinRead, BinWrite)]
   |          ^^^^^^^ the trait `BinRead` is not implemented for `&f32`
   |
   = help: the trait `BinRead` is implemented for `f32`
   = note: this error originates in the derive macro `BinRead` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is there any examples that allow writting `#[brw(map=map_fn)]`?

If it is possible, please adding it to the document, and if it cannot, please place a note about that.

Thanks:)

**Comment by csnover** [comment]
Thanks for your report! This is a manifestation of issue #179.

Applying the same function to input and output seems weird to me, but I guess if binrw refused to work with weird file formats then it would hardly be useful at all :-)

I’m not sure if it is possible to make this specific case work or not. If it were, it would involve the read side taking a map function with argument `&T` and turning it into a read of `T` plus a borrow for the map function. I am not sure right now how that would ever be possible since it cannot be an unconditional borrow and also the proc-macro does not have access to type information.

**Comment by Neutron3529** [comment]
> since it cannot be an unconditional borrow and also the proc-macro does not have access to type information.

I have an idea, just use the function's output (since it is the output of `bw`) as its input in case `br` failed to determine what to read.

Currently, it is `br` that don't know what to read (it infers the input to `()`)
```rust
error[E0277]: the trait bound `(): Borrow<f32>` is not satisfied
   --> src/data/building.rs:67:26
    |
67  |     #[br(map=|x|round_xy(x))]
    |                 -------- ^ the trait `Borrow<f32>` is not implemented for `()`
    |                 |
    |                 required by a bound introduced by this call
    |
note: required by a bound in `round_xy`
```
It will be fine if we switch the `()` to its output type, here, `f32`.

In a word, `br` use `fn`'s output if input is a `impl<something>` or generics, and `bw` use `fn`'s input if output returns an `impl`. In case `fn<T>(input: T) -> impl Something`, return an error.

**Comment by csnover** [comment]
How did it get from using `#[brw]` to `#[br]`? Is this a new approach/different issue? I just want to make sure I understand before saying any thing. Thanks!

**Comment by csnover** [comment]
Type inference in binrw comes from rustc. proc-macros do not have access to type information. `impl Trait` isn’t a concrete type, so this will never work. You’d need to use generic syntax `fn round_xy<T: core::borrow::Borrow>(val: T)` so you can manually specify the concrete type with `map(round_xy::<f32>)`. Using an additional closure works because it lets you specify the type explicitly in the closure. There is no getting around needing to specify the incoming type.

**Comment by Neutron3529** [comment]
> Type inference in binrw comes from rustc. proc-macros do not have access to type information. `impl Trait` isn’t a concrete type, so this will never work.

Although we cannot obtain its input, but we can obtain its output.

Since it is `#[brw(map = round_xy)]`, we could assume its input is the output function (fortunately, it is itself)'s output

Since the signature is `pub fn round_xy(val: impl std::borrow::Borrow<f32>) -> f32`, in case we cannot infer the input type, we could directly use its output (`f32` here) type instead.

**Comment by csnover** [comment]
binrw doesn’t infer anything, it relies on use of a hint function to decompose a function signature into component types that are then allowed to flow through the type graph (or whatever it is formally called) of rustc. This happens independently for read and write. It is not possible to determine in advance whether a write function returns `impl Trait` or a read function parameter is an `impl Trait` and then pick one so I don’t think what you are proposing is actually possible? If you can provide some proof of concept here that demonstrates how this could work, that would be cool.

**Comment by Neutron3529** [comment]
> If you can provide some proof of concept here that demonstrates how this could work, that would be cool.

The pseudo code could be shown as follows:

```rust
// brw implementations:
let mut parsed_type = parse_func_input();
if type.is_type::<()>() {
    parsed_type = parse_func_output();
}
```

Since currently unknown generic type or `impl T` will be inferred to `()`, it could directly goes to the `parse_func_output` branch, use the output as its input instead.

This is my logic, I do not have enough time examine what to modify in binrw_derive ( In case I have plenty of time, I'll try update syn to 2 first.. ), but such solution path seems reasonable.

**Comment by csnover** [comment]
Thank you for thinking more about this. A proof of concept needs to be actual working code, not pseudo-code. Only a working proof of concept demonstrates that some thing is possible in reality. The pseudo-code as written seems to me to rely on the thought that types can be converted to values at runtime, which is not true, or that proc-macros are type-aware, which is also not true.

Since this seems like a real edge case situation and it doesn’t sound like you’re having time to implement it yourself, I’m going to close this ticket as not planned for now, but please feel free to revisit it at any time if you find yourself with the time and motivation to do so. Thanks!
