### ISSUE TITLE
[Feature Request] update syn version in `binrw_derive` to `2`

### ISSUE THREAD

**Issue by Neutron3529** [jam1garner/binrw#285]
Currently lots of famous crate, including `clap_derive`, `thiserror_impl` uses `syn` with version 2, updating the version of syn to 2 might save several seconds of compile time.

I'm just wondering whether there exists such plan, since I tried update the syn version, but failed since `impl<T> quote::spanned::Spanned for SpannedValue<T>` never possible due to the `:Sealed` limitation.

I have to firstly read the full code and then I can updating the code.

I know how much the work is, thus I'm just wonder.

**Comment by csnover** [comment]
That trait sealing change is why the version is not updated. There’s no plan to update unless someone else does the work. Getting syn to do what we need it to do sucked (due to a combination of missing specialisation and the design of syn making it impossible to get access to certain things, though I don’t remember any more what those things are).
