### ISSUE TITLE
Named Arguments (or other solutions)

### ISSUE THREAD

**Issue by kitlith** [jam1garner/binrw#5]
## Background
ReadOptions contains `count`, which I think should be an argument to Vec and similar instead of beping part of implicit parser state. We can already write this as `type Args = (usize, <T as BinRead>::Args);`, but that results in `#[br(args(3, ()))]` (for i.e. Vec<u16>), and @jam1garner prefers `#[br(count = 3)]`.

# Option 1 (keep argument system as-is)
arguments stay the way they currently are. snover appears (appeared?) to prefer this option

We may be able to help differentiate the above case with something like `#[br(args(VecCount(3), ()))]`

### Ordered Named Arguments
add `const ArgNames: &'static [&'static str];` to the BinRead trait,
use static_assert / const_assert to check that the name for each callsite matches the name at the appropriate index in the implementation
perhaps, like the following variation, providing that name could be optional?

### Optional Unchecked Names
allow user to specify variable names that are explicitly ignored.
This way the user gets to clarify their code whenever and however they like,
and the implementation stays simple.

i.e. the goal with this implementation is that all of the following would work fine
 - `#[br(args(count = 3, inner = ()))]`
 - `#[br(args(3, ()))]`
 - `#[br(args(whatever = 3, ()))]`

# Option 2 (named arguments)
arguments become unordered, passed by name.
argument structs are autogenerated by the derive macro
calling syntax looks something like this (for `Vec<Vec<u8>>`): `#[br(args(count: 3, inner: args! { count: 6} ))]`
which de-sugars to:
```rust
{
    let mut args = Default::default();
    args.count = 3;
    {
        let args = &mut args.inner;
        args.count = 6;
    }
    args
}
```

thoughts: would we want to allow both ordered and unordered arguments? would we want to allow users to use both in a single arguments list?

# Any Other Options?
perhaps named arguments are still overkill for this scenario, idk. is there some other way of solving the original reason for investigating this?

**Comment by csnover** [comment]
I agree that it makes more sense for `count` to be an argument on `Vec` rather than a general thing, since I believe in surfacing errors at compile-time whenever possible. Using `count` on something which is not countable ought to be a compile-time error, and not a silent no-op at runtime. This is also a more flexible option for other composable wrapper types than having users guess arguments and order.

Regarding my own preference (mentioned under Option 1), I don’t have any particular affinity for the current argument system, I just have a non-preference for complex solutions like adding special traits or generating hash maps of types or developing DSLs that aren’t native/nearly native Rust syntax or adding extra lists of strings that map indexes to idents. At those levels of complexity, I prefer not to make any change.

I am in favour of following the approach I’ve described in chat, which is basically Option 2, where “named arguments” are implemented by making `BinRead::Args` a struct with named fields.

I am also OK with adding sugar to the proc-macro so users don’t need to explicitly specify all the types of inner structs, as described in Option 2. I feel like having no anonymous objects is a minor pain point for Rust generally, so it is probably a good idea to check for any Rust RFCs that propose a syntax for eliding type names when constructing objects (`<_> { foo: bar }` is my first instinct since that’s how type names are usually elided in superfish).

The biggest unresolved issue I see right now surrounds appropriate error handling and the issue of `Default`. While it makes sense that `T::Args` is going to have a default most of the time, `Vec<T>::Args` probably should *not*, since giving no count for this type ought to be a compile-time error. That would normally mean that the end user would need to specify the entire object tree manually, and I’m not sure how to reconcile this. At the least, going forward with `Vec<T>::Args` having a default for now is not any worse than the status quo, so if making it work causes the implementation to be too complex, it shouldn’t be a blocker since it’s not regressing functionality.

**Comment by csnover** [comment]
Regarding the defaults issue: it is possible to [trick the compiler into inferring a type](https://internals.rust-lang.org/t/short-enum-variant-syntax-in-some-cases/13113/9). This is a pretty gross hack, but it is not overly complicated. It would create an inconsistency since Default is still required for the children, but it would eliminate the requirement for Default on the root object since that type is known even if it is an alias.

The other upstream discussions I’ve read on type elision have most frequently mentioned using `_` to indicate an elided type, though there are more comments and links to discussions on the [structural records RFC](https://github.com/rust-lang/rfcs/pull/2584) that I haven’t read. Given what I *have* seen, the simplest usable syntax, and the one which seems most likely to end up being used upstream (if structural records don’t end up being a thing, since that RFC works by using backtracking) would probably be like:

`#[br(args { count: 1, inner: _ { … } })]` when the inner `T::Args` implements Default
`#[br(args { count: 1, inner: T::Args { … } })]` when it does not

**Comment by kitlith** [comment]
thanks for sharing that trick @csnover, i've extended a previous playground (that you made in discord i think?) to have the current target expansion with the addition of that trick: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8207f22e818c9bf3efc91a6e5fa6cc57

it's worth noting that instead of having special syntax of `_ { ... }` we can probably use the macro directly (maybe call it, `infer! { ... }` or `defaults! { ... }` or something?) and it can be a bit simpler than it currently is, as we won't need to worry about recursing into inner structs.

**Comment by jam1garner** [comment]
I also like the macro idea, I feel any syntax-heavy solution will likely be confusing to some subset of users, and no point in using potentially-confusing magic syntax with no in-language equivalent just to save a few keystrokes.

As for the naming, maybe something more noun-y like `args!{}`? so it would be something like `inner: args! { a: 1, b: 2 }`?

**Comment by kitlith** [comment]
> As for the naming, maybe something more noun-y like `args!{}`? so it would be something like `inner: args! { a: 1, b: 2 }`?

see, that was my original thought, but it is no longer tied to being arguments since we're forcing the compiler to properly infer the type. we can still call it that, of course, but technically we can use it for inferring the type of any struct whose values are being defaulted (as long as there is enough context ofc)

The one thing that bugs me is that we don't really have a way currently to seperate default args from non-default args (other than splitting them into a seperate struct, which i guess users can do) -- either every field in a particular struct is defaulted, or every field is provided.

it's probably not worth any additional complication to the implementation, though. (what comes to mind for me is using a crate to generate a type-safe builder for the arguments struct, then using the builder in place of setting fields directly. (this would also go back to being arguments specific, if we care about it being general)

**Comment by jam1garner** [comment]
Added by #21
