### ISSUE TITLE
How best to forward unevaluated offsets to child fields?

### ISSUE THREAD

**Issue by CJKay** [jam1garner/binrw#53]
Hi folks, I'm running into a situation where I have a file pointer in a child structure which has an offset only known after parsing most of the rest of the parent structure:

```rust
#[binread(little, import { file_data_offset: u64 })]
pub struct MorrowindFileEntry {
    ...

    #[binread(count = size)]
    #[binread(offset_after = file_data_offset)]
    pub data: FilePtr32<Vec<u8>>,

    ...
}

#[derive_binread]
#[derive(Debug)]
#[binread(little, magic = b"\x00\x01\x00\x00")]
pub struct MorrowindArchive {
    ...

    /// File entries.
    #[binread(count = header.file_count)]
    #[binread(args { inner: args! { file_data_offset: file_data_marker.pos } })]
    pub file_entries: Vec<MorrowindFileEntry>,

    ...

    /// Seek marker for the file data table.
    #[binread(temp)]
    file_data_marker: PosValue<()>,
}
```

I'm not entirely surprised this doesn't work, because my understanding is that `args` are evaluated immediately:

```rust
error[E0425]: cannot find value `file_data_marker` in this scope
  --> src/lib.rs:98:55
   |
98 |     #[binread(args { inner: args! { file_data_offset: file_data_marker.pos } })]
   |                                                       ^^^^^^^^^^^^^^^^ not found in this scope

```

But I'm not sure how else to solve this problem. Any input appreciated!

**Comment by jam1garner** [comment]
Some options:

1. rather than use a `FilePtr32` simply parse it as a `u32` and rather than eagerly parsing the data, provide an API in which a user can pass an `io::Read + io::Seek` to a `MorrowindFileEntry` in order to then read the contents of the file
2. replace usage of `file_data_marker` with offset calculation. depending on the contents of the `...`s this may be hard and/or impossible
3. use `seek_before` to skip `file_entries` then later seek back and read them once the location of `file_data_marker` is known. This may not be possible if `MorrowindFileEntry` isn't a fixed size
4. if and only if 2 and 3 aren't possible... you'd probably need to parse the entries -> seek backwards -> parse the entries again (yikes!) 

I am a bit partial to option 1 as I both think it is a better choice of large archives, but the downside is that you'd likely need two calls (one to `MorrowindArchive` to get the offset in some form (as a newtype, as a Reader adapter that is offset, etc), followed by another to `MarrowindFileEntry` in order to actually read the file (or possible produce another Reader adapter that lets the user read from the file)) to read from a file. This will make a more complex API but ultimately make your code better (for example if you want to have a CLI extract a single file then exit then reading every file's data is a bit pointless).

Let me know if none of these ideas fix the problems in a satisfying manner @CJKay and if so I'll try to work on a more general solution, as there's likely some room for improvement in cases where file formats require lookahead while parsing.
